### ISSUE TITLE
Very slow when parsing long strings of dashes inside code blocks

### ISSUE THREAD

**Issue by Nemo157** [rlidwka/render-readme#4]
Pulled out of an example containing a `multipart/form-data` upload. As more dashes are added the rendering seems to take exponentially more time.

```
→ time node -e 'require("render-readme")("\`\`\`\n------------\n\`\`\`")'                                      
node -e   0.48s user 0.07s system 102% cpu 0.541 total
→ time node -e 'require("render-readme")("\`\`\`\n------------------------------\n\`\`\`")'
node -e   60.09s user 1.42s system 105% cpu 58.180 total
```

**Comment by Nemo157** [comment]
Just tested against `markdown-it` to make sure it is related to `render-readme` specifically:

```
→ time node -e 'require("markdown-it")().render("\`\`\`\n------------------------------\n\`\`\`")'             
node -e   0.11s user 0.02s system 96% cpu 0.137 total
```

**Comment by rlidwka** [comment]
Thanks for reporting it. This seems to be an issue in `highlight.js`, I opened a ticket [here](https://github.com/isagalaev/highlight.js/issues/769).

**Comment by rlidwka** [comment]
This bug should be fixed now.

**Comment by Nemo157** [comment]
Awesome, thanks :smile:
