### ISSUE TITLE
Allow base64 images

### ISSUE THREAD

**Issue by simonhoss** [rlidwka/render-readme#6]
Hi,

I would like to have base64 images, so I changed the allowedSchemes.

```javascript
allowedSchemes    : $w('http https mailto github-windows github-mac data'),
```

I would recommend to enable this for everyone using this module. What do you think?

**Comment by rlidwka** [comment]
This module is designed to replicate exactly what github sanitizer does.

And github doesn't allow data uri, probably for this reason:

```md
[click me](data:application/javascript,alert('XSS'))
```

**Comment by simonhoss** [comment]
This makes sense. Thanks.
